"""Procedural pixel-art sprites (16x16 grid, PAL-01 palette).

Each sprite is a list of 16 strings, 16 chars each. Char -> color from a
per-sprite palette map (keys refer to palette.PALETTE). '.' = transparent.

Motifs (ART_DIRECTION.md): ziggurat steps, cuneiform wedges, brick courses,
occult rings, pastel magic accents on dark base tones.

All sprites are generated by generate.py into assets/sprites/*.png. The
generator is deterministic — editing these grids and re-running the script
regenerates every asset identically.
"""

from __future__ import annotations

from tools.asset_gen.palette import PALETTE

# ---------------------------------------------------------------------------
# Player (Warrior) — small hero: dark teal tunic, cyan trim, gold belt, sword.
# ---------------------------------------------------------------------------
PLAYER = {
    "rows": [
        "......cc........",
        ".....cccc.......",
        ".....cccc.......",
        "....cccccc......",
        "...wwwwwwww.....",
        "...wsseessw.....",
        "...ssggggss.....",
        "....gggggg......",
        "....gGGGGg......",
        "....GGGGGG......",
        "....gGGGGg......",
        ".....gggg.......",
        "....bb..bb......",
        "....bb..bb......",
        "....bb..bb......",
        "................",
    ],
    "palette": {
        "c": "cyan", "w": "bone", "s": "stone", "e": "ash",
        "g": "gold", "G": "brick", "b": "sand",
    },
}

# ---------------------------------------------------------------------------
# Greybox Dummy — shambling clay golem: brick body, sand joints, gold eyes.
# ---------------------------------------------------------------------------
DUMMY = {
    "rows": [
        "................",
        "......bb........",
        ".....bbbb.......",
        ".....bbbb.......",
        "....bbbbbb......",
        "...bbbbbbbb.....",
        "...bBBbbBBb.....",
        "...bbbbbbbb.....",
        "...bbggggbb.....",
        "...bbbbbbbb.....",
        "....bbbbbb......",
        "....ss..ss......",
        "....ss..ss......",
        "...ss....ss.....",
        "...ss....ss.....",
        "................",
    ],
    "palette": {
        "b": "brick", "B": "sand", "g": "gold", "s": "ash",
    },
}

# ---------------------------------------------------------------------------
# Elite Dummy — larger, gold trim, violet aura pixel ring.
# ---------------------------------------------------------------------------
ELITE = {
    "rows": [
        "......vv........",
        ".....vvvv.......",
        "....vbbbbv......",
        "...vbbbbbbv.....",
        "...bbbbbbbb.....",
        "..bbbbbbbbbb....",
        "..bbBBbbBBbb....",
        "..bbbbbbbbbb....",
        "..bbggggggbb....",
        "..bbggggggbb....",
        "..bbbbbbbbbb....",
        "...bbbbbbbb.....",
        "...GG....GG.....",
        "..GGG....GGG....",
        "..GG......GG....",
        "................",
    ],
    "palette": {
        "v": "violet", "b": "brick", "B": "sand", "g": "gold", "G": "stone",
    },
}

# ---------------------------------------------------------------------------
# Boss (Warden of the First Floor) — 32x32 ziggurat-stone golem.
# Runes glow violet in phase 1; the scene swaps to pink for phase 2.
# ---------------------------------------------------------------------------
BOSS = {
    "rows": [
        "......................VV................",
        ".....................VVVV...............",
        "....................VVVVVV..............",
        "...................VVbbbbVV.............",
        "..................VVbbbbbbVV............",
        ".................VVbbbbbbbbVV...........",
        "................VVbbbbbbbbbbVV..........",
        "...............VVbbbbbbbbbbbbVV.........",
        "..............VVbbbbbbbbbbbbbbVV........",
        ".............VVbbbbbbbbbbbbbbbbVV.......",
        "............VVbbbbbbbbbbbbbbbbbbVV......",
        "...........VVbbbbbbbbbbbbbbbbbbbbVV.....",
        "..........VVbbbbbbbbbbbbbbbbbbbbbbVV....",
        ".........VVbbbbbbbbbbbbbbbbbbbbbbbbVV...",
        "........VVbbbbbbbbbbbbbbbbbbbbbbbbbbVV..",
        ".......VVbbbbbbbbbbbbbbbbbbbbbbbbbbbbVV.",
        "......VVbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbVV",
        "......VbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbV.",
        "......VbbbbbbbbbbVVVVVVVVVVbbbbbbbbbbbV.",
        "......VbbbbbbbbbbVggggggggVbbbbbbbbbbbV.",
        "......VbbbbbbbbbbVggggggggVbbbbbbbbbbbV.",
        "......VbbbbbbbbbbVVVVVVVVVVbbbbbbbbbbbV.",
        "......VbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbV.",
        "......VVbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbVV",
        ".......VVbbbbbbbbbbbbbbbbbbbbbbbbbbbbVV.",
        "........VVbbbbbbbbbbbbbbbbbbbbbbbbbbVV..",
        ".........VVbbbbbbbbbbbbbbbbbbbbbbbbVV...",
        "..........VVbbbbbbbbbbbbbbbbbbbbbbVV....",
        "...........VVbbbbbbbbbbbbbbbbbbbbVV.....",
        "............VVbbbbbbbbbbbbbbbbbbVV......",
        ".............VVbbbbbbbbbbbbbbbbVV.......",
        "..............VVbbbbbbbbbbbbbbVV........",
    ],
    "palette": {
        "V": "violet", "b": "stone", "g": "gold",
    },
}

# ---------------------------------------------------------------------------
# Village building tiers (plot -> tier1). 32x32, ziggurat step roof,
# gold lamplight windows. Tier 0 = bare plot (sand + bricks + stakes).
# ---------------------------------------------------------------------------
BUILDING_PLOT = {
    "rows": [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "..bb..bb..bb..bb..bb..bb..bb....",
        ".ss..ss..ss..ss..ss..ss..ss.....",
        "................................",
    ],
    "palette": {"b": "brick", "s": "sand"},
}

BUILDING_TIER1 = {
    "rows": [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................gggg............",
        "..............gggggggg..........",
        "............gggggggggggg........",
        "..........bbbbbbbbbbbbbb........",
        ".........bbbbbbbbbbbbbbbb.......",
        "........bbbbbbbbbbbbbbbbbb......",
        ".......bbbbbbbbbbbbbbbbbbbb.....",
        "......bbbbbbbbbbbbbbbbbbbbbb....",
        "......bbbbbbbbbbbbbbbbbbbbbb....",
        "......bbbbbbbbbbbbbbbbbbbbbb....",
        "......bbbbbbbbbbbbbbbbbbbbbb....",
        "......bbbbbbbbbbbbbbbbbbbbbb....",
        "......bbbbbbbbbbbbbbbbbbbbbb....",
        "......bbb..............bbb......",
        "......bbb..............bbb......",
        "......bbb..............bbb......",
        "......bbb..............bbb......",
        "......bbb..............bbb......",
        "......bbb..............bbb......",
        "......bbbbbbbbbbbbbbbbbbbbbb....",
        "................................",
        "................................",
        "................................",
        "................................",
    ],
    "palette": {"b": "brick", "g": "gold"},
}

# ---------------------------------------------------------------------------
# NPC — small robed figure. Hood color is chosen per service at call time
# (loadout=cyan, run_prep=green, upgrades=gold); the row uses 'H' as the
# hood color key which generate.py replaces.
# ---------------------------------------------------------------------------
NPC_BASE = {
    "rows": [
        "................",
        ".....HHHHHH.....",
        "....HHHHHHHH....",
        "....HHssssHH....",
        "....HHssssHH....",
        ".....HHHHHH.....",
        "....bbbbbbbb....",
        "...bbbbbbbbbb...",
        "...bbbbbbbbbb...",
        "...bbbbbbbbbb...",
        "...bbbbbbbbbb...",
        "....bbbbbbbb....",
        "....ss....ss....",
        "...sss....sss...",
        "...ss......ss...",
        "................",
    ],
    "palette": {
        "H": "cyan",  # replaced per service
        "s": "bone", "b": "ash",
    },
}

# ---------------------------------------------------------------------------
# Tiles — 16x16.
# ---------------------------------------------------------------------------
TILE_FLOOR = {
    "rows": [
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
        "nnnnnnnnnnnnnnnn",
    ],
    "palette": {"n": "night"},
}

TILE_WALL = {
    "rows": [
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
        "ssssssssssssssss",
    ],
    "palette": {"s": "shadow"},
}

# ---------------------------------------------------------------------------
# Effects.
# ---------------------------------------------------------------------------
GLOW_RING = {
    "rows": [
        "...cccccc...",
        "..cccccccc..",
        ".cccccccccc.",
        ".cc......cc.",
        "cc........cc",
        "cc........cc",
        "cc........cc",
        ".cc......cc.",
        ".cccccccccc.",
        "..cccccccc..",
        "...cccccc...",
    ],
    "palette": {"c": "cyan"},
}


ALL_SPRITES: dict[str, dict] = {
    "player": PLAYER,
    "dummy": DUMMY,
    "elite": ELITE,
    "boss": BOSS,
    "building_plot": BUILDING_PLOT,
    "building_tier1": BUILDING_TIER1,
    "npc": NPC_BASE,
    "tile_floor": TILE_FLOOR,
    "tile_wall": TILE_WALL,
    "glow_ring": GLOW_RING,
}


def rows_to_pixels(
    rows: list[str], palette_map: dict[str, str]
) -> list[list[tuple[int, int, int, int]]]:
    """Convert string rows + palette map to RGBA pixel rows."""
    pixels: list[list[tuple[int, int, int, int]]] = []
    for row in rows:
        pixel_row: list[tuple[int, int, int, int]] = []
        for char in row:
            if char == ".":
                pixel_row.append((0, 0, 0, 0))
                continue
            color_name = palette_map.get(char)
            if color_name is None:
                raise ValueError(f"unknown palette key '{char}'")
            rgb = PALETTE[color_name]
            pixel_row.append((rgb[0], rgb[1], rgb[2], 255))
        pixels.append(pixel_row)
    return pixels


def make_npc(hood_color: str = "cyan") -> dict:
    """NPC sprite with the hood color set per service."""
    palette = dict(NPC_BASE["palette"])
    palette["H"] = hood_color
    return {"rows": NPC_BASE["rows"], "palette": palette}
